version: "3"
services:
  cache:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      allnetwork:
        ipv4_address: 172.20.0.5
networks:
  default:
    external:
      name: allnetwork
  allnetwork:
    external: true
